"""Add quantity and purchase_price to watchlist

Revision ID: a2c0f56b20f0
Revises: bb9d2b2e05e6
Create Date: 2025-09-07 11:47:33.044848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c0f56b20f0'
down_revision: Union[str, Sequence[str], None] = 'bb9d2b2e05e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_ticker'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.add_column('watchlist', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.alter_column('watchlist', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_watchlist_ticker'), table_name='watchlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_watchlist_ticker'), 'watchlist', ['ticker'], unique=False)
    op.alter_column('watchlist', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('watchlist', 'purchase_price')
    op.drop_column('watchlist', 'quantity')
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolios_pkey'))
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_index(op.f('ix_portfolios_ticker'), 'portfolios', ['ticker'], unique=False)
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    # ### end Alembic commands ###
